services:
  file_storing_db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: file_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
  file_analysis_db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: analysis_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5433:5432"

  file_storing_service:
      build:
        context: ./FileStoringService
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8000:8000"
      depends_on:
        - file_storing_db

  file_analisys_service:
      build:
        context: ./FileAnalisysService
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8001:8001"
      depends_on:
        - file_analysis_db

  nginx:
    image: nginx:alpine
    volumes:
      - ./APIGateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - file_storing_service
      - file_analisys_service